condense_wildcard_suffixes = true
error_on_line_overflow = true
fn_params_layout = "Vertical"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "Vertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
