name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    if: |
      contains(github.event.commits.*.modified, 'Cargo.toml') ||
      contains(github.event.commits.*.modified, 'Cargo.lock') ||
      contains(github.event.commits.*.modified, 'src/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build
        run: cargo build --verbose --release
  test:
    if: |
      contains(github.event.commits.*.modified, 'Cargo.toml') ||
      contains(github.event.commits.*.modified, 'Cargo.lock') ||
      contains(github.event.commits.*.modified, 'src/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Run tests
        run: cargo test --verbose --all-features
  clippy_check:
    if: |
      contains(github.event.commits.*.modified, 'Cargo.toml') ||
      contains(github.event.commits.*.modified, 'Cargo.lock') ||
      contains(github.event.commits.*.modified, 'src/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  fmt_check:
    if: |
      contains(github.event.commits.*.modified, 'Cargo.toml') ||
      contains(github.event.commits.*.modified, 'Cargo.lock') ||
      contains(github.event.commits.*.modified, 'src/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run cargo fmt check
        run: cargo fmt --all --check
